// Generated by gencpp from file ball_chaser/ObjectFound.msg
// DO NOT EDIT!


#ifndef BALL_CHASER_MESSAGE_OBJECTFOUND_H
#define BALL_CHASER_MESSAGE_OBJECTFOUND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ball_chaser
{
template <class ContainerAllocator>
struct ObjectFound_
{
  typedef ObjectFound_<ContainerAllocator> Type;

  ObjectFound_()
    : is_found(false)  {
    }
  ObjectFound_(const ContainerAllocator& _alloc)
    : is_found(false)  {
  (void)_alloc;
    }



   typedef uint8_t _is_found_type;
  _is_found_type is_found;





  typedef boost::shared_ptr< ::ball_chaser::ObjectFound_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ball_chaser::ObjectFound_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectFound_

typedef ::ball_chaser::ObjectFound_<std::allocator<void> > ObjectFound;

typedef boost::shared_ptr< ::ball_chaser::ObjectFound > ObjectFoundPtr;
typedef boost::shared_ptr< ::ball_chaser::ObjectFound const> ObjectFoundConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ball_chaser::ObjectFound_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ball_chaser::ObjectFound_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ball_chaser

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ball_chaser': ['/home/student/roboticsND/final-project/src/ball_chaser/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ball_chaser::ObjectFound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ball_chaser::ObjectFound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ball_chaser::ObjectFound_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ball_chaser::ObjectFound_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_chaser::ObjectFound_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ball_chaser::ObjectFound_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ball_chaser::ObjectFound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8adcb5649ca708386016da412c13201d";
  }

  static const char* value(const ::ball_chaser::ObjectFound_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8adcb5649ca70838ULL;
  static const uint64_t static_value2 = 0x6016da412c13201dULL;
};

template<class ContainerAllocator>
struct DataType< ::ball_chaser::ObjectFound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ball_chaser/ObjectFound";
  }

  static const char* value(const ::ball_chaser::ObjectFound_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ball_chaser::ObjectFound_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_found\n\
";
  }

  static const char* value(const ::ball_chaser::ObjectFound_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ball_chaser::ObjectFound_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectFound_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ball_chaser::ObjectFound_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ball_chaser::ObjectFound_<ContainerAllocator>& v)
  {
    s << indent << "is_found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_found);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALL_CHASER_MESSAGE_OBJECTFOUND_H
